name: .NET Core

on:
  push:
    branches: [ master ]
  pull_request:
    branches: '*'
jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
          dotnet-version: ${{ env.DOTNET_VERSION }} 
      
      # Run dotnet build and publish
    - name: dotnet build and publish
      run: |
          dotnet build --configuration Release
